influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'env.influxdb'

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  links:
    - influxdb

botnet:
  image: botnet
  container_name: botnet
  environment:
    - TWITCH_CLIENT_ID=$TWITCH_CLIENT_ID
    - OAUTH_TOKEN=$OAUTH_TOKEN
  links:
    - influxdb
